version: '3.7'
services:
  postgres:
    container_name: covid_test
    image: postgres:13.1
    volumes:
      - './postgres/data:/var/lib/postgresql/data'
      - './postgres/local:/home'
    environment:
      POSTGRES_MULTIPLE_DATABASES: covid_test
      POSTGRES_USER: covid_test
      POSTGRES_PASSWORD: covid_test
    ports:
      - '5432:5432'
volumes:
  pgdata:
    name: covid_test
